export interface Flight {
    airline: string;
    airlineLogo: string;
    duration: string;
    departureTime: string;
    arrivalTime: string;
    stops: string;
    layover: string;
    price: string;
    isRoundTrip: boolean;
  }
  
 export const flights: Flight[] = [
    {
      airline: "Hawaiian Airlines",
      airlineLogo: "/logos/hawaiian.png",
      duration: "16h 45m",
      departureTime: "7:00AM",
      arrivalTime: "4:15PM",
      stops: "1 stop",
      layover: "2h 45m in HNL",
      price: "$624",
      isRoundTrip: true,
    },
    {
      airline: "Japan Airlines",
      airlineLogo: "/logos/japan.png",
      duration: "18h 22m",
      departureTime: "7:35 AM",
      arrivalTime: "12:15 PM",
      stops: "1 stop",
      layover: "50m in HKG",
      price: "$663",
      isRoundTrip: true,
    },
    {
      airline: "Hawaiian Airlines",
      airlineLogo: "/logos/hawaiian.png",
      duration: "18h 04m",
      departureTime: "8:20AM",
      arrivalTime: "2:15PM",
      stops: "1 stop",
      layover: "1h 50m in PVG",
      price: "$690",
      isRoundTrip: true,
    },
    {
      airline: "Delta",
      airlineLogo: "/logos/delta.png",
      duration: "18h 52m",
      departureTime: "9:47 AM",
      arrivalTime: "4:15 PM",
      stops: "1 stop",
      layover: "4h 05m in ICN",
      price: "$756",
      isRoundTrip: true,
    },
    {
      airline: "Hawaiian Airlines",
      airlineLogo: "/logos/hawaiian.png",
      duration: "16h 05m",
      departureTime: "11:15 AM",
      arrivalTime: "7:45 PM",
      stops: "Nonstop",
      layover: "",
      price: "$837",
      isRoundTrip: true,
    },
    {
      airline: "Hawaiian Airlines",
      airlineLogo: "/logos/hawaiian.png",
      duration: "15h 45m",
      departureTime: "10:55 AM",
      arrivalTime: "8:15 PM",
      stops: "Nonstop",
      layover: "",
      price: "$839",
      isRoundTrip: true,
    },
    {
      airline: "Delta",
      airlineLogo: "/logos/delta.png",
      duration: "18h 20m",
      departureTime: "1:00 PM",
      arrivalTime: "9:15 PM",
      stops: "1 stop",
      layover: "4h 45m in ICN",
      price: "$886",
      isRoundTrip: true,
    },
    {
      airline: "EVA Air",
      airlineLogo: "/logos/eva.png",
      duration: "18h 55m",
      departureTime: "2:15 PM",
      arrivalTime: "11:15 PM",
      stops: "1 stop",
      layover: "2h 45m in HNL",
      price: "$913",
      isRoundTrip: true,
    },
    {
      airline: "Korean Air",
      airlineLogo: "/logos/korean.png",
      duration: "22h 37m",
      departureTime: "6:45 PM",
      arrivalTime: "7:15 PM",
      stops: "2 stops",
      layover: "2h 45m in PVG, ...",
      price: "$989",
      isRoundTrip: true,
    },
    {
      airline: "Japan Airlines",
      airlineLogo: "/logos/japan.png",
      duration: "20h 23m",
      departureTime: "7:00AM",
      arrivalTime: "4:15PM",
      stops: "2 stops",
      layover: "2h 45m in HKG, ...",
      price: "$624",
      isRoundTrip: true,
    },
    {
      airline: "Japan Airlines",
      airlineLogo: "/logos/japan.png",
      duration: "16h 45m",
      departureTime: "7:00AM",
      arrivalTime: "4:15PM",
      stops: "Nonstop",
      layover: "",
      price: "$1,079",
      isRoundTrip: true,
    },
    {
      airline: "EVA Air",
      airlineLogo: "/logos/eva.png",
      duration: "16h 10m",
      departureTime: "7:00AM",
      arrivalTime: "4:15PM",
      stops: "Nonstop",
      layover: "",
      price: "$1,114",
      isRoundTrip: true,
    },
    {
      airline: "Korean Air",
      airlineLogo: "/logos/korean.png",
      duration: "14h 37m",
      departureTime: "7:20AM",
      arrivalTime: "1:15PM",
      stops: "Nonstop",
      layover: "",
      price: "$1,347",
      isRoundTrip: true,
    },
    {
      airline: "Air France",
      airlineLogo: "/logos/airfrance.png",
      duration: "19h 45m",
      departureTime: "9:00AM",
      arrivalTime: "1:15PM",
      stops: "1 stop",
      layover: "5h 45m in HNL",
      price: "$1,392",
      isRoundTrip: true,
    },
    {
      airline: "Emirates",
      airlineLogo: "/logos/emirates.png",
      duration: "16h 55m",
      departureTime: "7:10AM",
      arrivalTime: "4:35PM",
      stops: "1 stop",
      layover: "2h 45m in HKG",
      price: "$1,403",
      isRoundTrip: true,
    },
  ];